<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnK</name>
   <tag></tag>
   <elementGuidId>5f370b13-9b0a-4692-9f2b-c71a05f90f12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.FPdoLc.lJ9FBc > center > input[name=&quot;btnK&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='btnK'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;ค้นหาด้วย Google&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50985c81-b466-4871-9440-a56749020cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gNO89b</value>
      <webElementGuid>cee3b481-8438-4531-a2eb-70b088af1b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ค้นหาด้วย Google</value>
      <webElementGuid>b6ac9523-6d02-4f1b-a007-a1aec1581f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ค้นหาด้วย Google</value>
      <webElementGuid>e0a20f1b-2477-43c5-bb34-3263bd4dd55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnK</value>
      <webElementGuid>4e24394a-77f5-4c55-9a74-4861b409e986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>feaa9726-cd80-458c-a191-ca62e63a01c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>46082780-c6d8-492f-854f-3e9c0e936400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>67f1ac12-d014-42b6-b4c7-8596f6ed68c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>0ahUKEwid_vn3i9yEAxXz7jgGHbCuCJsQ4dUDCBE</value>
      <webElementGuid>f4d4fd24-bcd2-4686-9ddf-94b2c96bdf27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;L3eUgb&quot;]/div[@class=&quot;o3j99 ikrT4e om7nvf&quot;]/form[1]/div[1]/div[@class=&quot;A8SBwf&quot;]/div[@class=&quot;FPdoLc lJ9FBc&quot;]/center[1]/input[@class=&quot;gNO89b&quot;]</value>
      <webElementGuid>9645f5f6-4ff6-488d-86c5-5ceed882d9f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='btnK'])[2]</value>
      <webElementGuid>06988a83-a7ec-4c24-9081-1781a07e017f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/center/input</value>
      <webElementGuid>05e38d0a-4bb6-4c9f-bf3f-05b04ab4f984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnK' and @type = 'submit']</value>
      <webElementGuid>70d8e520-c046-4093-a74b-dd088a93fe56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
